- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: Install File beat and pre-requisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items:
      - apt-transport-https
      - filebeat
  register: get_result
  until: get_result is success
  retries: 3
  delay: 2          

- name: Copy the config file
  command: 'filebeat modules enable logstash nginx'

- name: Copy the config file
  template:
    src: filebeat.yml.j2
    dest: "/etc/filebeat/filebeat.yml"
  notify: Restart Filebeat

